name: Update Tweets

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 mins
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run scraper
        run: python fetch_bescom.py

      - name: Commit and push if changed
        run: |
          git config user.name "bescom-bot"
          git config user.email "bescom-bot@users.noreply.github.com"
          git add tweets.json
          git diff --cached --quiet || git commit -m "Update tweets"
          git push
